source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'portal-to-work' do
    pod 'SnapKit', '~> 5.0.0'
    pod 'SmartystreetsSDK'
    pod 'PromiseKit/CorePromise'
end
